# Generated by Django 3.1.1 on 2020-09-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeS',
            new_name='Like',
        ),
    ]
