# Generated by Django 3.1.1 on 2020-09-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20200913_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='kin_of_pizza',
            field=models.CharField(choices=[('MEA', 'Meat'), ('VEGE', 'Vegetarian'), ('VEGA', 'Vegan'), ('None', '')], default='None', max_length=4),
        ),
    ]
