# Generated by Django 3.1.1 on 2020-09-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('pizza', '0003_pizza_kin_of_pizza'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'pizza')},
        ),
    ]
